# Data configuration
data:
  train_images_path: "~/data/mnist/train-images.idx3-ubyte"
  train_labels_path: "~/data/mnist/train-labels.idx1-ubyte"
  test_images_path: "~/data/mnist/t10k-images.idx3-ubyte"
  test_labels_path: "~/data/mnist/t10k-labels.idx1-ubyte"
  batch_size: 512
  num_workers: 4

# Model configuration
model:
  input_dim: 784  # 28x28 MNIST images
  hidden_dim: 128
  output_dim: 10  # 10 classes for MNIST
  num_layers: 2
  activation_fn: "relu"
  dropout: 0.2

# Training configuration
training:
  num_epochs: 100
  learning_rate: 0.001
  optimizer: "adam"  # Options: adam, sgd
  optimizer_params:
    weight_decay: 0.0001
    beta1: 0.9
    beta2: 0.999
  criterion: "cross_entropy"  # Options: cross_entropy, mse

# Experiment tracking
experiment:
  name: "mlp"
  save_dir: "results/mlp"

# Device configuration
device: "cuda:0" # defaults to the first GPU available
